services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: find-a-friend-api
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: find-a-friend-db
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
