# PETS
POST http://localhost:3333/pets
Content-Type: application/json

{
   "name": "Yara",
   "about": "Yara é uma cachorra muito bonita e inteligente",
   "age": "Idoso",
   "size": "Pequenino",
   "energy_level": 5,
   "level_of_independence": "Médio",
   "environment": "Ambiente amplo",
   "city": "São Paulo",
   "organization_id": "0012a511-25dc-4c29-8aa9-b3bfa37edeb3"
}
###

# ORGANIZATIONS

POST http://localhost:3333/organizations
Content-Type: application/json

{
   "responsible_name": "ORG 1",
   "email": "org1@gmail.com",
   "password": "123456",
   "cep": "1234567890",
   "city": "São Paulo",
   "address": "Rua das Flores, 123",
   "phone": "1234567890"
}
   